In [4]:
import pandas as pd

df = pd.read_csv("../data/Phishing_Email.csv")

print(df.shape)
df.head()

(18650, 3)

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [5]:
print(df.columns)

Index(['Unnamed: 0', 'Email Text', 'Email Type'], dtype='object')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18650 entries, 0 to 18649
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  18650 non-null  int64
 1   Email Text  18634 non-null  object
 2   Email Type  18650 non-null  object
dtypes: int64(1), object(2)
memory usage: 437.2+ KB

In [6]:
df.isnull().sum()

Unnamed: 0     0
Email Text    16
Email Type     0
dtype: int64

In [7]:
df = df.drop(columns=["Unnamed: 0"])

df = df.dropna()

print(df.shape)
df.head()

(18634, 2)

                                          Email Text      Email Type
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email
1  the other side of * galicismos * * galicismo *...      Safe Email
2  re : equistar deal tickets are you still avail...      Safe Email
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email
4  software at incredibly low prices ( 86 % lower...  Phishing Email

In [15]:
df["Email Type"].value_counts()

Series([], Name: Email Type, dtype: int64)

In [16]:
df["Email Type"] = df["Email Type"].map({
    "Safe Email": 0,
    "Phishing Email": 1
})

df.head()

                                          Email Text  Email Type
0  re : 6 . 1100 , disc : uniformitarianism , re ...         NaN
1  the other side of * galicismos * * galicismo *...         NaN
2  re : equistar deal tickets are you still avail...         NaN
3  \nHello I am your hot lil horny toy.\n    I am...         NaN
4  software at incredibly low prices ( 86 % lower...         NaN

In [17]:
X = df["Email Text"]
y = df["Email Type"]

print(X.shape)
print(y.shape)

(18634,)
(18634,)

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. Added ngram_range=(1, 2) to capture word pairs
# 2. Added min_df=2 to drop ultra-rare random words/typos
vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=5000,
    ngram_range=(1, 2),  
    min_df=2             
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [49]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [50]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9669975851891602

In [51]:
# Before We Touch Streamlit

# Let's save the model.

In [52]:
import joblib

In [53]:
joblib.dump(model, "../models/phishing_model.pkl")
joblib.dump(vectorizer, "../models/vectorizer.pkl")
print("Model Saved Successfully")

Model Saved Successfully

In [54]:
#Next

#Let's verify the model works on custom emails.

#Create a new cell:

In [62]:
sample_email = """
Congratulations!

Your account has been suspended.

Click the link below immediately to verify your credentials.

http://fake-bank-login.com
"""

In [63]:
sample_vector = vectorizer.transform([sample_email])

prediction = model.predict(sample_vector)

print(prediction)

[1]

In [61]:
sample_email = """
 hi brother 
i hope u good , we are going to trip tommarow are u willing to come 
"""

In [58]:
sample_vector = vectorizer.transform([sample_email])

prediction = model.predict(sample_vector)

print(prediction)

[0]

In [59]:
# Assuming you used a LabelEncoder or mapped them manually
print(df['Email Type'].value_counts())

0    11322
1     7312
Name: Email Type, dtype: int64

In [60]:
# Replace 'model' and 'vectorizer' with your variable names
import numpy as np

feature_names = np.array(vectorizer.get_feature_names_out())
coefficients = model.coef_[0]

# Get top 20 words that scream "Phishing" to your model
top_phishing = feature_names[np.argsort(coefficients)[-20:]]
print("Words predicting Phishing:", top_phishing)

Words predicting Phishing: ['viagra' 'visit' 'best' 'reply' 'rolex' 'info' 'removed' 'hello' 'site'
 'life' 'sightings' 'save' 'spamassassin sightings' 'email' '2004' 'money'
 'free' 'remove' '2005' 'click']

In [21]:
df["Email Type"].isnull().sum()

18634

In [23]:
df["Email Type"].unique()

array([nan])

In [24]:
import pandas as pd

df = pd.read_csv("../data/Phishing_Email.csv")

df = df.drop(columns=["Unnamed: 0"])

df = df.dropna()

print(df["Email Type"].unique())

['Safe Email' 'Phishing Email']

In [25]:
df["Email Type"].value_counts()

Safe Email        11322
Phishing Email     7312
Name: Email Type, dtype: int64

In [26]:
df["Email Type"].unique()

array(['Safe Email', 'Phishing Email'], dtype=object)

In [27]:
df["Email Type"] = df["Email Type"].map({
    "Safe Email": 0,
    "Phishing Email": 1
})

print(df["Email Type"].unique())
print(df["Email Type"].isnull().sum())

[0 1]
0

In [28]:
X = df["Email Text"]
y = df["Email Type"]

In [29]:
print(y.unique())
print(y.isnull().sum())

[0 1]
0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=5000
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)